[tool.pdm.dev-dependencies]
dev = [
    "ipykernel<7.0.0,>=6.29.5",
]

[tool.pdm.build]
includes = []

[tool.uv.workspace]
members = ["venv"]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
authors = [
    {name = "Leonid Chesnikov", email = "leonid.chesnikov@gmail.com"},
]
license = {text = "MIT"}
requires-python = "<4.0,>=3.12"
dependencies = [
    "transformers @ git+https://github.com/huggingface/transformers.git",
    "diffusers<1.0.0,>=0.32.2",
    "pydantic<3.0.0,>=2.10.6",
    "langchain<1.0.0,>=0.3.20",
    "llama-cpp-python<1.0.0,>=0.3.8",
    "vllm<1.0.0,>=0.7.3",
    "llama-index-core<1.0.0.0,>=0.12.23.post2",
    "langchain-core<1.0.0,>=0.3.44",
    "langchain-openai<1.0.0,>=0.3.8",
    "langchain-huggingface<1.0.0,>=0.1.2",
    "llama-index<1.0.0,>=0.12.23",
    "ipykernel<7.0.0,>=6.29.5",
    "ipywidgets<9.0.0,>=8.1.5",
    "accelerate<2.0.0,>=1.5.2",
    "yandex-cloud-ml-sdk<1.0.0,>=0.4.1",
    "cachetools<6.0.0,>=5.5.2",
    "openai<2.0.0,>=1.66.3",
    "python-pptx<2.0.0,>=1.0.2",
    "ruff>=0.11.0",
    "webcolors>=24.11.1",
    "langchain-community>=0.3.20",
    "openai-agents>=0.0.7",
    "pydantic-ai>=0.0.43",
    "loguru>=0.7.3",
    "agno>=1.2.15",
    "aiogram>=3.19.0",
    "pdf2image>=1.17.0",
]
name = "pg-ai-core"
version = "0.1.0"
description = "AI-core for agents to many of projects"
readme = "README.md"

[dependency-groups]
dev = [
    "ipykernel<7.0.0,>=6.29.5",
]

[tool.ruff]
line-length = 120
target-version = "py310"
fix = false
show-fixes = true
output-format = "grouped"
extend-exclude = ["*.pyi"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = [
  "A",      # flake8-builtins
  "ANN",    # flake8-annotations
  "ARG",    # flake8-unused-arguments
  "ASYNC",  # flake8-async
  "B",      # flake8-bugbear
  "C4",     # flake8-comprehensions
  "C90",    # mccabe
  "DTZ",    # flake8-datetimez
  "E",      # pycodestyl
  "EM",     # flake8-errmsg
  "ERA",    # eradicate
  "F",      # pyflakes
  "FBT",    # flake8-boolean-trap
  "I",      # isort
  "INT",    # flake8-gettext
  "N",      # pep8-naming
  "PL",     # Pylint
  "PERF",   # Perflint
  "PT",     # flake8-pytest-style
  "RET",    # flake8-return
  "S",      # flake8-bandit
  "SLF",    # flake8-flake8-self
  "T20",    # flake8-print
  "TRY",    # tryceratops
  "SIM",    # flake8-simplify
  "UP",     # pyupgrade
  "W",      # pycodestyle
]
ignore = ["ANN101", "E501", "T201"]
ignore-init-module-imports = true

[tool.ruff.lint.extend-per-file-ignores]
"**/{tests,docs,tools}/*" = ["E402", "S101", "ANN401", "ANN001", "S603", "ARG001"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.isort]
lines-between-types = 1
lines-after-imports = 2

[tool.ruff.lint.mccabe]
# Flag errors (C901) whenever the complexity level exceeds 6.
max-complexity = 6

[tool.ruff.lint.pylint]
allow-dunder-method-names = ["__tablename__", "__table_args__", "__post_init__"]
