[tool.poetry]
name = "pg-ai-core"
version = "0.1.0"
description = "AI-core for agents to many of projects"
authors = ["Leonid Chesnikov <leonid.chesnikov@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
transformers = {extras = ["torch"], version = "^4.49.0"}
diffusers = "^0.32.2"
pydantic = "^2.10.6"
langchain = "^0.3.20"
llama-cpp-python = "^0.3.8"
vllm = "^0.7.3"
llama-index-core = "^0.12.23.post2"
langchain-core = "^0.3.44"
langchain-openai = "^0.3.8"
langchain-huggingface = "^0.1.2"
llama-index = "^0.12.23"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
